Add pre-release builds/tests for CentOS Stream 9.
GoogleCloudPlatform/guest-test-infra pull request #353
Opened 2022-02-01 22:19 UTC by zmarano

Also, add Debian 11 to our integ tests.

2022-02-01 22:19 UTC, zmarano commented
/hold

2022-02-01 22:19 UTC, zmarano commented
/assign @hopkiw

2022-02-02 21:07 UTC, hopkiw requested changes

2022-02-02 21:21 UTC, zmarano commented on concourse/pipelines/guest-package-build.yaml
> +      - task: build-package-image-el-9
Removed the test for now. el-9 was consistent with el-8 and el-7.

2022-02-03 21:00 UTC, hopkiw approved these changes

2022-02-03 21:06 UTC, zmarano commented
/unhold

2022-02-03 22:09 UTC, hopkiw approved these changes

2022-02-03 22:10 UTC, merged